image: atlassian/default-image:2
pipelines:
  default:
    - step:
         services:
          - docker 
         script:
            - export IMAGE_NAME=pradeep34946/mysql:$BITBUCKET_COMMIT
            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME 